// Code generated by Kitex v0.6.2. DO NOT EDIT.

package favoriteinfoservice

import (
	"context"
	api "gateway/rpcApi/favoriteInfo/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryFavoriteList(ctx context.Context, Req *api.FavoriteInfoQueryFavoriteListRequest, callOptions ...callopt.Option) (r *api.FavoriteInfoQueryFavoriteListResponse, err error)
	FavoriteAction(ctx context.Context, Req *api.FavoriteInfoFavoriteActionRequest, callOptions ...callopt.Option) (r *api.FavoriteInfoFavoriteActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFavoriteInfoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFavoriteInfoServiceClient struct {
	*kClient
}

func (p *kFavoriteInfoServiceClient) QueryFavoriteList(ctx context.Context, Req *api.FavoriteInfoQueryFavoriteListRequest, callOptions ...callopt.Option) (r *api.FavoriteInfoQueryFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFavoriteList(ctx, Req)
}

func (p *kFavoriteInfoServiceClient) FavoriteAction(ctx context.Context, Req *api.FavoriteInfoFavoriteActionRequest, callOptions ...callopt.Option) (r *api.FavoriteInfoFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, Req)
}
