// Code generated by Kitex v0.6.2. DO NOT EDIT.

package feedprotobuf

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "gateway/microService/feed/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetFeed(ctx context.Context, Req *api.DouyinFeedRequest, callOptions ...callopt.Option) (r *api.DouyinFeedResponse, err error)
	PublishVideo(ctx context.Context, Req *api.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *api.DouyinPublishActionResponse, err error)
	GetAuthorVideoList(ctx context.Context, Req *api.DouyinPublishListRequest, callOptions ...callopt.Option) (r *api.DouyinPublishListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFeedProtoBufClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFeedProtoBufClient struct {
	*kClient
}

func (p *kFeedProtoBufClient) GetFeed(ctx context.Context, Req *api.DouyinFeedRequest, callOptions ...callopt.Option) (r *api.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFeed(ctx, Req)
}

func (p *kFeedProtoBufClient) PublishVideo(ctx context.Context, Req *api.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *api.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishVideo(ctx, Req)
}

func (p *kFeedProtoBufClient) GetAuthorVideoList(ctx context.Context, Req *api.DouyinPublishListRequest, callOptions ...callopt.Option) (r *api.DouyinPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAuthorVideoList(ctx, Req)
}
