version: "3"
services:
  comment-redis:
    image: redis:5.0.9-alpine
    container_name: comment-redis
    restart: always
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"
  comment-mysql:
    image: mysql:8.0
    container_name: comment-mysql
    restart: always
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=commentMysql
      - MYSQL_ROOT_PASSWORD=enid123456
      - TZ=Asia/Shanghai
  etcd1:
    image: quay.io/coreos/etcd:v3.4.13
    volumes:
      - ./data/etcd/data:/etcd_data
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd1
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=tiktok1etcd4
      - ETCD_INITIAL_CLUSTER_STATE=new



